### ISSUE TITLE
Add a link to the past scores in the live page when there are no any live contest

### ISSUE THREAD

**Issue by JeelRajodiya** [Triellis/clash-of-codes#52]

**Comment by Codesmith28** [comment]
ohk

**Comment by Codesmith28** [comment]
ill create an enhancements branch for the same

**Comment by Codesmith28** [comment]
Most of the time live nhi chale toh aa koru saru na laage 

Toh ek kaam karne ...
Uper aa text rakh...
Maybe highlight kar deje 

And niche just kaik tamaro funny pic/ video muki dyo 

😂✨
Like aavu : the battle is yet to begin, however, you can look at our goblins 😂

**Comment by JeelRajodiya** [comment]
> Most of the time live nhi chale toh aa koru saru na laage 
> 
> Toh ek kaam karne ...
> Uper aa text rakh...
> Maybe highlight kar deje 
> 
> And niche just kaik tamaro funny pic/ video muki dyo 
> 
> 😂✨
> Like aavu : the battle is yet to begin, however, you can look at our goblins 😂

Too much thai gayu, I'll resolve this issue
